actorSystemName: MymicroserviceActorSystem
persistenceActorName: MymicroservicePersistenceActor
applicationPersistenceId: MymicroservicePersistenceId


logging:
  level: INFO
  loggers:
    no.jansoren: DEBUG
